devices([
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPhone 16e",
  "iPad Pro 13-inch (M5)",
  "iPad Pro 11-inch (M5)"
])

languages(["en-CA"])

scheme("ScooterCompanion")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)

launch_arguments(["--screenshot-mode"])
xcargs("CODE_SIGNING_ALLOWED='YES' -allowProvisioningUpdates")
