devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone SE (3rd generation)"
])

languages(["en-CA"])

scheme("GT3Companion")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)

launch_arguments(["--screenshot-mode"])
