name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Generate Xcode project
        run: |
          brew install xcodegen
          xcodegen generate
      - name: Build iOS App
        run: |
          xcodebuild build \
            -project GT3Companion.xcodeproj \
            -scheme "GT3CompanionCI" \
            -destination "generic/platform=iOS Simulator" \
            -configuration Debug \
            -skipPackagePluginValidation \
            CODE_SIGNING_ALLOWED=NO \
            EXCLUDED_ARCHS=x86_64
